### ISSUE TITLE
Offer a way to set the space between figboxes in \SetFigboxLayout

### ISSUE THREAD

**Issue by FrankMittelbach** [borisveytsman/fitbox#2]
Right now the size for figures is calculated as

```
\@tempdima=\textwidth
\ifnum#3>1\relax\@tempdima=0.9\@tempdima\fi
\divide\@tempdima by #3\relax       % <-- could be inside \ifnum
```
Besides that it probably should be `\columnwidth` not `\textwidth` the problem with this approach is that if you have a different number of figures side by side the total will come out different (assuming that in the actual figure env you always separate them by, say, a space---leaving different amounts of white space to the left and right (or even getting bigger than the available width, for example if in the source you separate by a `\quad`).

My suggestion would be to do
```
\SetFigboxLayout[extra captlines]{rows}{cols}[separation]`
```
with "separation" defaulting to a "space". Then you could write:
```
\SetFigboxLayout{2}{3}[\quad]
```
with a code roughly like
```
\@tempdima=\textwidth
\ifnum#3>1\relax
  \settowidth\@tempdimb{#4}%
  \advance\@tempdima-#3\@tempdimb  % or suitable \...expr
  \advance\@tempdima\@tempdimb
  \divide\@tempdima by #3\relax
\fi
```

**Comment by borisveytsman** [comment]
I think a key-val interface would be more intuitive

**Comment by FrankMittelbach** [comment]
certinainly more flexible (and modern :-))
